version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: db:3306   # Assurez-vous que le port est inclus
      WORDPRESS_DB_USER: sio
      WORDPRESS_DB_PASSWORD: Sio2024  
      WORDPRESS_DB_NAME: db_sio
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - db
    command: sh -c "sleep 10 && apache2-foreground"  # Attente, bien que cela puisse être amélioré

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: db_sio           
      MYSQL_USER: sio
      MYSQL_PASSWORD: Sio2024           
      MYSQL_ROOT_PASSWORD: root_password  # Optionnel : mot de passe root pour MySQL
    volumes:
      - db:/var/lib/mysql

volumes:
  wordpress:
  db:
